### ISSUE TITLE
Hello, when is the next update plan for the tutorial?

### ISSUE THREAD

**Issue by cargo-youth** [skyzh/mini-lsm#7]

**Comment by skyzh** [comment]
It depends on the circumstances. I’m also looking forward to some feedbacks of existing parts before going down to writing.

**Comment by cargo-youth** [comment]
I just started trying to learn and can learn a lot about rust and LSM from this project. I think the design of this tutorial book is very reasonable. I hope to share it with every related knowledge lover around me.

**Comment by godruoyi** [comment]
hi @skyzh, I'm glad you created this interesting project. I've been following the tutorial for the past few days, and I find it difficult because I'm new to Rust and don't understand why things are done the way they are. could you please take some time to provide more details?

For example, we could break it down into several parts (project initialization/task 1/task 2, etc.) and have separate branches or PRs for each part, which would make it easier for us to learn.

Now we only have a mini-lsm-starter and a completed mini-lsm, and we're confused because we don't know how it was completed step by step.

**Comment by skyzh** [comment]
Making it a step-by-step tutorial seems like a good idea. I might need to take some time thinking of what is the best way to deliver the content.

**Comment by caicancai** [comment]
hi @skyzh,  Thank you very much for this tutorial, I have learned some rust basics and am working on this tutorial. If you need help, I think it's very helpful (if I can help)

**Comment by caicancai** [comment]
> Making it a step-by-step tutorial seems like a good idea. I might need to take some time thinking of what is the best way to deliver the content.

hi @skyzh,  Thank you very much for this tutorial, I have learned some rust basics and am working on this tutorial. If you need help, I think it's very helpful (if I can help)

**Comment by ScottLinnn** [comment]
Looking forward for updates +1!

**Comment by skyzh** [comment]
i have rewritten everything up to what we had in 2023 and week/part 2 of this tutorial will be available soon! https://skyzh.github.io/mini-lsm/
